version: "3.2" 
services:
  web:
    image: yat011/transportation_countdown:latest
    ports:
      - "5000:8080"
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=
    working_dir: /app/
    command: node server/server.js
